#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm install firebase@4.1.3
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - cd functions
  - npm install
  - cd ..

script:
  - ng build --prod --aot

after_success:
  - npm run precache
  - firebase use --token $FIREBASE_TOKEN esint-v2
  - firebase deploy -m "Deployed from Travis-CI" --non-interactive --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: always
    on_success: change